#! /bin/tcsh
# GOAL: take input from keyboard not cmd args. store in list. while loop
# read arguments individually from the user
echo -n "enter a few numbers: "
set list = ($<)
echo "Input is $list"
# calc and print the average 
set sum = 0
set count = 1
set avg = 0
#use a while loop instead of foreach to calculate results
while ( $count <= $#list )
    #echo "start count = $count"
    @ sum = $sum + $list[$count]
    #echo "new sum = $sum"
    @ count++ 
    #echo "end count = $count"
end

# sub 1 from count; extra counting
@ count --
echo "sum = $sum"
@ avg  = $sum / $count
echo "avg = $avg "


