#! /bin/tcsh
# read arguments individually from the user
echo -n "enter a few numbers: "
set list = ($<)
echo "Input is $list"
# calc and print the average 
set sum = 0
set count = 1
set avg = 0

while ( $count <= $#list )
    echo "start count = $count"
    @ sum = $sum + $list[$count]
    echo "new sum = $sum"
    @ count++ 
    echo "end count = $count"
end

# sub 1 from count; extra counting
@ count --
@ avg  = $sum / $count
echo "avg = $avg "


