#! /bin/bash
# Syntax: junk [options] targetFileList
# Options: -l       list the current contents of the .junk directory
#          -n       shows the number of files in the .junk directory
#                       and the amount of memory space they consume
#          --help   display a brief descrition about this script
# Script 'junk' is replacement for the 'rm' commmand.
# Argument targetFileList is a list of filenames.
# Rather than removing the target files, 'junk' moves them
#   into the subdirectory .junk in the user's home directory.
# If the .junk subdirectory does not exist, it is automatically created.
# If a file with the same name as the file to be moved already
#   exists in .junk directory, keep the newer version of 
#   that file in the subdirectory.


